version: "3.8"

volumes:
  db-data:

services:
  anchor:
    build:
      context: .
    ports:
      - "$RPC_PORT:18550"
    entrypoint:
      - "/app/mev-boost"
      - "-mainnet"
    environment:
      - "LOG_LEVEL=debug"
      - "BOOST_LISTEN_ADDR=0.0.0.0:18550"
      - "RELAYS=$RELAYS" # scheme://pubkey@host,scheme://pb2@host2, e.g. http://0xtest@baton.url:8080,...